typedef unsigned char uint8;
typedef char int8;
typedef int int32;
typedef unsigned int uint32;
typedef unsigned int uint;
typedef unsigned short uint16;
typedef unsigned short ushort;
typedef long long int64;
typedef unsigned long long uint64;
typedef unsigned char uchar;
typedef long unsigned int size_t;